name: highlight
description: An interop example with the Highlight.js syntax highlighter library
# version: 1.0.0
#homepage: https://www.example.com
#author: Jermaine Oppong <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^1.0.0
